### ISSUE TITLE
graphile-build:warn TypeError: getComputedColumnDetails is not a function

### ISSUE THREAD

**Issue by fuad008** [graphile/pg-aggregates#11]
### app.js

`
const http = require('http');
const { postgraphile } = require('postgraphile');
const PgAggregatesPlugin = require('@graphile/pg-aggregates').default;
const ConnectionFilterPlugin = require('postgraphile-plugin-connection-filter');

http.createServer(
    postgraphile(process.env.DATABASE_URL, process.env.schema, {
        watchPg: true,
        graphiql: true,
        enhanceGraphiql: true,
        allowExplain: (req) => true,
        appendPlugins: [ConnectionFilterPlugin, PgAggregatesPlugin],
        showErrorStack: true,
        extendedErrors: ['hint', 'detail', 'errcode'],
        graphileBuildOptions: {
            connectionFilterRelations: true,
            connectionFilterComputedColumns: false,
            connectionFilterSetofFunctions: false,
        },
    }),
).listen(process.env.PORT);
`

### Dependencies

"postgraphile": "^4.5.5",
 "postgraphile-plugin-connection-filter": "^1.1.3",
 "@graphile/pg-aggregates": "^0.1.0"

### Dockerfile

FROM node:alpine
LABEL description="Instant high-performance GraphQL API for your PostgreSQL database https://github.com/graphile/postgraphile"

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

CMD [ "node", "app.js" ]

###Error 
When running node app.js, I get the following error

graphile    |     at GraphQLInputObjectType.getFields (/app/node_modules/graphql/type/definition.js:1017:27)
graphile    |     at Object.newWithHooks (/app/node_modules/postgraphile-core/node_modules/graphile-build/node8plus/makeNewBuild.js:702:36)
graphile    |     at /app/node_modules/@graphile/pg-aggregates/dist/AddHavingAggregateTypesPlugin.js:173:31
graphile    |     at Array.reduce (<anonymous>)
graphile    | Recoverable error occurred:
graphile    | 2021-04-23T18:59:15.472Z graphile-build:warn TypeError: getComputedColumnDetails is not a function
graphile    |     at /app/node_modules/@graphile/pg-aggregates/dist/AddHavingAggregateTypesPlugin.js:209:55
graphile    |     at Array.reduce (<anonymous>)
graphile    |     at fields (/app/node_modules/@graphile/pg-aggregates/dist/AddHavingAggregateTypesPlugin.js:199:90)
graphile    |     at fields (/app/node_modules/postgraphile-core/node_modules/graphile-build/node8plus/makeNewBuild.js:563:27)
graphile    |     at resolveThunk (/app/node_modules/graphql/type/definition.js:438:40)
graphile    |     at defineInputFieldMap (/app/node_modules/graphql/type/definition.js:1056:18)

**Comment by benjie** [comment]
![Screenshot_20210423_201702](https://user-images.githubusercontent.com/129910/115919560-e62e0480-a470-11eb-8637-a7692ce3cdba.png)
