### ISSUE TITLE
Filtering by totalCount

### ISSUE THREAD

**Issue by Claire-Couppie** [graphile/pg-aggregates#25]
### Feature description

I would like to be able to filter a query using the count of a related object 

### Motivating example

I would like for instance to filter by number of warehouses of a company:

```
query MyQuery {
  companies {
    nodes {
      warehouses(
        filter: {totalCount: {greaterThan: 2}}){
        totalCount
      }
    }
  }
}
```

I saw this kind of use case in this issue in `postgraphile-plugin-connection-filter` : https://github.com/graphile-contrib/postgraphile-plugin-connection-filter/issues/152#issuecomment-821776142

However, I couldn't manage to use the proposed solution for all possible values, it worked only for greater than 0. It would also be easier to use I think with the above example, which was also what was tried initially by the linked issue's author.

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [x] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
Please could you share the query that you attempted with `distinctCount` - I'd expect a distinctCount over a unique column (such as the primary key) to give the result you're hoping for.

Further, please can you expand on "it worked only for greater than 0" - what were the other cases you tried and what happened in those cases - an error? incorrect results? Please share as much detail as you can.

A rough definition of the relevant tables/columns/constraints in your database would also be helpful.
