### ISSUE TITLE
Add relation aggregates to aggregates

### ISSUE THREAD

**Issue by robhanlon22** [graphile/pg-aggregates#6]
### Feature description

It would be really useful to be able to get summary aggregates of relations, so one could answer questions about related data.

### Motivating example

Given this query:

```graphql
{
  allUsers {
    nodes {
      ordersByUserId {
        aggregates {
          sum {
            price
          }
        }
      }
    }
  }
}
```

It would useful to also get the aggregated prices for all of the orders, something like this:

```graphql
{
  allUsers {
    aggregates {
      ordersByUserId {
        sum {
          price
        }
      }
    }
    nodes {
      ordersByUserId {
        aggregates {
          sum {
            price
          }
        }
      }
    }
  }
}
```

Or to avoid creating children of `aggregates` that are not aggregates: 

```graphql
{
  allUsers {
    aggregates {
      sum {
        ordersByUserId {
          price
        }
      }
    }
    nodes {
      ordersByUserId {
        aggregates {
          sum {
            price
          }
        }
      }
    }
  }
}
```

Or even this…?

```graphql
{
  allUsers {
    aggregates {
      sum {
        ordersByUserId(attribute: ORDERS_BY_USER_ID_PRICE)
      }
    }
    nodes {
      ordersByUserId {
        aggregates {
          sum {
            price
          }
        }
      }
    }
  }
}
```

Anyhow, the details in the resulting schema could be worked out with some iteration :) These examples are kind of trivial because it would be possible to get the sum of the order prices by querying `allOrders` directly. However, if you went one level deeper (imagine a multi-tenant system here, where an `account` is a company or some higher-order entity):

```graphql
{
  allAccounts {
    aggregates {
      sum {
        price
        usersByAccountId {
          price
          ordersByUserId {
            price
          }
        }
      }
    }
  }
}
```

Then you end up with some really powerful capabilities, where you can get aggregates at many levels, which could by used to create useful dashboards, analytics features, etc.

### Breaking changes

None—this would just expand the capabilities of the existing aggregates.

### Supporting development

I [tick all that apply]:

- [x] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [x] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
```graphql
{
  allAccounts {
    aggregates {
      sum {
        price }}}}
```

^ This is quite clear; something like: `select sum(accounts.price) from accounts`


```graphql
{
  allAccounts {
    aggregates {
      sum {
        usersByAccountId {
          price } } } } }
```

^ This is less clear, is this a single value across all accounts:

```sql
select sum(users.price)
from accounts
inner join users
on (accounts.id = users.account_id)
```

?

Or is it grouped by the account ID, so for each account id you get a value:

```sql
select accounts.id, sum(users.price)
from accounts
inner join users
on (accounts.id = users.account_id)
group by accounts.id
```

?

**Comment by michaelbridge** [comment]
Hi benjie! Thanks for another great addition to the postgraphile ecosystem!

The second example above is the critical use case; the desire is to group and aggregate from two different tables.  I'd go so far as to say this is a universal desire since it is common in database design to store values in a separate table from metadata (so that the metadata need not be repeated for every value).

In any case, I could imagine the `groupBy` argument accepting something akin to what's used in `postgraphile-plugin-connection-filter`, in place of the current `groupBy` enum.

I'd be curious to hear whether you think this might ever be in scope.  I've been poking around the source to see if it might be possible.

**Comment by benjie** [comment]
I think you can do that by adding a custom grouping which is a subquery to fetch the related data.

**Comment by KazimirPodolski** [comment]
I'm trying to do exactly this, but currently there are some obstacles:
* `isSuitableType` is a check based only on a type, while it should be type + column, so you can e.g. add grouping only for id:
  ```sql
  select sum(users.price)
  from users
  group by (select accounts.id from accounts where accounts.id = users.account_id)
  ```
  Currently `isSuitableType` makes this grouping available for all number-like columns (if you enable it for `account_id`), which is meaningless.
* `pgAggregateGroupBySpecs` enables aggregation only for single column, i.e. `sqlFrag` = `__local_123__.<column>`. If in prev. example you want to join by more than one column, you can't (I know a workaround with pg settings, but it is super ugly and verbose)
* In general, "group by arbitrary expression" would be great to have. Currently it's doable, but there are a lot of ugliness
