### ISSUE TITLE
All attributes appear in aggregates, even if disabled by behaviors

### ISSUE THREAD

**Issue by nckswt** [graphile/pg-aggregates#66]
### Summary

Using this plugin, I wanted to disable `property.created_at` but it shows up in the aggregate (see screenshot)
![image](https://github.com/graphile/pg-aggregates/assets/634615/a4334ee3-12c0-4d50-a9c6-b5f974637864)

Using `graphile behavior debug pgCodecAttribute property.created_at` my final string for this `property.created_at` attribute is 

```
Final string:
  -list -insert -update -delete -filterBy -orderBy -* -select -query -connection -order -base -filter -aggregates
```

Shouldn't it be disabled in the `distinctCount` aggregate?

### Steps to reproduce

Use PgAggregates and set an attribute's behavior to `-*`.

### Expected results

I would not expect that attribute to appear in the schema.

### Actual results

That attribute appears in the schema.

### Additional context

[Discord thread](https://discord.com/channels/489127045289476126/498852330754801666/1234916980092571758)

**Comment by benjie** [comment]
From a quick search of the codebase (`v5` branch) for the word `behavior`, it looks like the `aggregates` behavior has only been implemented for resources (tables) and relations (FKs) at this time. The relevant places would need to call `build.behavior.pgCodecAttributeMatches(...)` and skip adding the relevant field/etc if false. Are you interested in taking that on? It could be months before I get around to it.
