### ISSUE TITLE
getComputedColumnDetails is not a function

### ISSUE THREAD

**Issue by aviallon** [graphile/pg-aggregates#7]
### Summary
When adding `@graphile/pg-aggregates` `--append-plugin`, I have this warning:
```
graphile-build:warn TypeError: getComputedColumnDetails is not a function
  graphile-build:warn     at /home/aviallon/Nextcloud/Pro/Prestas/Sprint/Avocat/plateforme_juridique/angularelectronapp/node_modules/@graphile/pg-aggregates/dist/AddHavingAggregateTypesPlugin.js:209:55
```
I am using PG 13.2. I ran `yarn upgrade`, still had the issue, retried with `npx yarn-deduplicate && yarn`, kept having the issue.
I have one computed column, returning a custom type, which might be the issue?

### Steps to reproduce

Do the above.

### Expected results

I expect to not have this warning.

### Actual results

As summary says.

### Additional context

```
postgraphile@^4.11.0
@graphile/pg-pubsub@^4.11.0
@graphile/subscriptions-lds@^4.11.0
@graphile/lru@4.11.0
@graphile/pg-aggregates@^0.0.2
@graphile/lds@4.11.0
```

### Sponsoring
- [x] I am a Graphile backer

**Comment by benjie** [comment]
Hey @aviallon! This is built on an experimental new API, so as the README states:

> Requires PostGraphile v4.12.0-alpha.0 or higher.

(You'll need to update all the other modules to that version too.)

**Comment by aviallon** [comment]
Oh, ok. That's why. Thank you :)
I guess I should have RTFM then ^^

**Comment by benjie** [comment]
Closing as solved :+1:
